### ISSUE TITLE
Error: stdout maxBuffer exceeded

### ISSUE THREAD

**Issue by shaine** [lob/generate-changelog#10]
Hello,

We have a large codebase we're trying to apply this tool to. I'm getting the "No commits found" error, but after doing a little debugging in the lib, I discovered that it's not failing to find commits but rather finding way too many commits.

<img width="448" alt="screenshot 2016-12-02 15 00 04" src="https://cloud.githubusercontent.com/assets/204734/20851904/4644e648-b8a0-11e6-8863-ece4056bec1e.png">

Thoughts? I'll keep digging to see if there's anything node offers to get around this. Thanks!

**Comment by robinjoseph08** [comment]
Interesting, I didn't know there was a max size to the stdout buffer. I wonder if there's a way to stream the contents instead. I'll try to take a look whenever I can, but any PRs are welcome!

**Comment by shaine** [comment]
Heh, yeah I was surprised too. Our workaround was to just add a tag around the first commit where we started using this commit message format, which works fine. I suppose a stopgap solution would be to catch this specific message to let people know that there's too many commits for the tool to read - I don't really have any ideas about parsing a stdout stream right now.

**Comment by tvardy** [comment]
Setting `execOptions` for `child_process` should help...
Tried this on a 2.5 year old repo with thousands of commits.
