### ISSUE TITLE
git and bitbucket commit url issue

### ISSUE THREAD

**Issue by ShahnawazAli93** [lob/generate-changelog#12]
Its not generating correct url for bitbucket commits

In git the commit url has the following format:
https://github.com/nodejs/node/commit/96e8e869c0
(notice the 'commit' stirng in url)

The same commit in bitbucket will have an extra 's' in 'commit':
https://bitbucket.org/nodejs/node/commits/96e8e869c0
(notice the 'commits' stirng in url)

Take a look at it

**Comment by robinjoseph08** [comment]
Hi @ShahnawazAli93!

Looks like you're right. This is coming from [this line here](https://github.com/lob/generate-changelog/blob/572a6f552c340da4468026730e4069da4d96f707/lib/writer.js#L83). We should probably have a function that generates the URL so we can put git-provider specific logic there.

We'll try to get to it whenever we can, but we also welcome PRs if you want to put one up!

**Comment by maurocarrero** [comment]
@ShahnawazAli93 @robinjoseph08 I'd need this fix, I guess from the last comment date, that this is not ongoing. Let me know if i can help.

**Comment by ShahnawazAli93** [comment]
@maurocarrero Thanks for reminding about this, let me check and see if it still exists. If it does I will send a PR.
