### ISSUE TITLE
Breaking change support

### ISSUE THREAD

**Issue by rtrompier** [lob/generate-changelog#20]
Hi,
Can you add support to display breaking change in the final changelog ?
I use commitizen to add breaking.

Thanks ;)

**Comment by rtrompier** [comment]
See my PR #21 ;)

**Comment by rtrompier** [comment]
Can you please check my PR ? 

Thanks

**Comment by JasonCust** [comment]
Just added a new PR (#34) that encapsulated the requested changes for the previous PR by @rtrompier.

**Comment by robinjoseph08** [comment]
Closed via #34
