### ISSUE TITLE
cli -exclude split fails as undefined

### ISSUE THREAD

**Issue by andrewdc** [lob/generate-changelog#22]
I have tried passing every format of comma separated list I can even imagine, and I still get:

```
.npm-packages/lib/node_modules/generate-changelog/lib/cli.js:8
  return val.split(',');
```
Maybe I'm just totally blanking on the format, but I have tried a zillion combinations. Here are a few:

changelog -p -x [chore, test]
changelog -p -x ['chore', 'test']
changelog -p -x  chore, test
changelog -p -x  "chore, test"
changelog -p -x 'chore', 'test'
changelog -p, -x=[chore]

etc.

I'm probably just doing it wrong, but thought I would ask.
Thanks.

**Comment by robinjoseph08** [comment]
@andrewdc thanks for reaching out! Looks like this is actually a bug with the `-x` flag. We should have a fix out soon, and we'll let you know when a new version has been cut!

**Comment by robinjoseph08** [comment]
v1.3.1 is now published! Thanks again for the bug report!

**Comment by andrewdc** [comment]
Awesome! Thanks so much @robinjoseph08.

**Comment by andrewdc** [comment]
Just pulled and tested this myself. -x flag is working. Awesome! Thanks.
