### ISSUE TITLE
Support commit ranges

### ISSUE THREAD

**Issue by bennyn** [lob/generate-changelog#27]
Creating changelogs requires [semantic commit messages](https://seesparkbox.com/foundry/semantic_commit_messages) and the execution of `changelog -M`, `changelog -m` or `changelog -p`. Is there also possibility to create a changelog from a commit range? 

I am thinking of something like: `changelog 420c945...2a83752`.

GitHub supports showing a comparison of two SHA1 hashes, like:
- https://github.com/welovecoding/website/compare/420c945...2a83752

**Comment by robinjoseph08** [comment]
Hey @bennyn!

Right now, the way this package figures out the commit range is by using tags as anchors (i.e. give me all commits from the last tag to the most recent commit). 

What you're suggesting is another way to generate this commit range (by passing it in manually). I think that totally makes sense and would accept a PR that allowed for that in addition to the current way of range generation. I think making an optional CLI flag makes the most sense. 

But you also mention the semantic commit messages and the usage of `[Mmp]`. If I'm understanding correctly, this change wouldn't affect those aspects at all, right? You'll still have to format your commit messages correctly, and you still either pass in one of those flags. Is that correct?

I just want to make sure we're on the same page in regards to what this feature entails so there's no ambiguity when someone actually works on it.

Thanks!

**Comment by ffflorian** [comment]
> If I'm understanding correctly, this change wouldn't affect those aspects at all, right? You'll still have to format your commit messages correctly, and you still either pass in one of those flags. Is that correct?

I also understood it like this and implemented it accordingly in the pull request :slightly_smiling_face:

**Comment by bennyn** [comment]
@robinjoseph08 You understood me correctly. We are on the same page. :) 

I just want to be able to define the commit range myself.
I think that's what has been implemented with https://github.com/lob/generate-changelog/pull/28?

**Comment by bennyn** [comment]
Almost two weeks since my last comment... Time for another push. 😀

**Comment by robinjoseph08** [comment]
@bennyn @ffflorian sorry for the delay here! I hope to get to #28 very soon (within the week)!
