### ISSUE TITLE
Make the pull request number a link to the PR

### ISSUE THREAD

**Issue by TalonLaurens** [lob/generate-changelog#30]
Hi,

It would be really cool if the PR numbers in the changelog would be links to the PRs, just like the commit messages are links to the commits.

I'd even be willing to look into this myself if you can point me to the right lines of code :)

**Comment by robinjoseph08** [comment]
Hi @TalonLaurens,

That would be an awesome feature! The logic for writing out the commits in the markdown format lies in [this loop here](https://github.com/lob/generate-changelog/blob/7912ef07de138d517e8254e6f519d44a6d605974/lib/writer.js#L74-L95), so I think that'll be where the additions will go. We'd definitely welcome a PR, thanks!

**Comment by altJake** [comment]
Hi @robinjoseph08 ,

I am a colleague of @TalonLaurens and have added the needed code for that feature,
feel free to have a look at the PR and review it

Thanks!
