### ISSUE TITLE
[Error: no commits found]

### ISSUE THREAD

**Issue by akashdeep-singh** [lob/generate-changelog#8]
I'm getting the following error on a mac system:
[Error: no commits found]
There were 3 commits in the repo when I first saw the issue, and I added two more commits to test, but itt still wouldn't work.

**Comment by robinjoseph08** [comment]
Hmm that's odd. Could you let me know what version of `git` you're using? Also, when you run the following command, what is outputted?

```sh
git log -E --format=%H%n%s%n%b%n===END===
```

**Comment by akashdeep-singh** [comment]
I realized the issue was with that particular developer not pushing with --tags, causing local tags to not be pushed into remote.
