### ISSUE TITLE
Ignore Merge commit

### ISSUE THREAD

**Issue by w3apps** [lob/generate-changelog#9]
I'm using the Pull Request strategy for my project and everytime a new request is approved and merged into master there are 2 commits, the initial one and a "merge commit". In this case the changelog appears empty. Somehow it doesn't like the merge commit. Any idea how to get around this? I can't get rid of the merge commit.

**Comment by robinjoseph08** [comment]
Hi @w3apps,

We actually do the same thing! Whenever we merge in PRs, it adds two commits to the commit log: the one of the actual change that we made and then the GitHub-generated merge commit. But our changelogs still generate just fine. Here's an example of the [merge commits](https://github.com/lob/eslint-config-lob/commits/master) and the correct [changelog](https://github.com/lob/eslint-config-lob/blob/master/CHANGELOG.md).

Are you sure you're following the commit message format that is required by this package? Can you paste an example of the commit message of the commit you made (not the merge commit)? Or better yet, if the project is open-sourced, can you just link to the repo?

Let us know!

**Comment by w3apps** [comment]
Hi @robinjoseph08 ,

Appreciate the quick reply! After a bit more digging I realized I was cloning the repo with -depth 1 which meas I had no repo history and git describe wasn't working.

**Comment by robinjoseph08** [comment]
No problem, glad you got it working!
